# 1.Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [1]:
import numpy as np

In [5]:
a1 = np.array([1, 11, 111])
a2 = np.array([5, 11, 100])
print("Is greater?",np.greater(a1,a2))
print("Is greater and equal?",np.greater_equal(a1,a2))
print("Is less than?",np.less(a1,a2))
print("Is less than or equal?",np.less_equal(a1,a2))

Is greater? [False False  True]
Is greater and equal? [False  True  True]
Is less than? [ True False False]
Is less than or equal? [ True  True False]


# 2.Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [6]:
a1=np.zeros(10)
print("An array of 10 zeros:")
print(a1)
a2=np.ones(10)
print("An array of 10 ones:")
print(a2)
a3=np.ones(10)*5
print("An array of 10 fives:")
print(a3)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


# 3.Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.

In [7]:
a1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Original array:")
print(a1)
print("Sum of all elements:")
print(np.sum(a1))
print("Sum of each column:")
print(np.sum(a1, axis=0))
print("Sum of each row:")
print(np.sum(a1, axis=1))

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Sum of all elements:
78
Sum of each column:
[15 18 21 24]
Sum of each row:
[10 26 42]


# 4.Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [9]:
print("Addition:")
print(np.add(5, 4))
print("Subtraction:")
print(np.subtract(5, 4))
print("Multiplication:")
print(np.multiply(5, 4))
print("Division:")
print(np.divide(5, 4))

Addition:
9
Subtraction:
1
Multiplication:
20
Division:
1.25


# 5.Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degree.

In [12]:
angles = np.array([0, 30, 45, 60, 90])
print("sine of given angles:")
print(np.sin(angles * np.pi / 180.))
print("cosine of angles given:")
print(np.cos(angles * np.pi / 180.))
print("tangent of angles given:")
print(np.tan(angles * np.pi / 180.))

sine of given angles:
[0.         0.5        0.70710678 0.8660254  1.        ]
cosine of angles given:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tangent of angles given:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
