## Question 1:
Try to create the backpropagation and feedforward in python by creating function

In [1]:
import numpy as np

# Considering sample data as follows
# X = (hours studying, hours sleeping), y = score on test
xAll = np.array(([2, 9], [1, 5], [3, 6], [5, 10]), dtype=float)  # input data
y = np.array(([92], [86], [89]), dtype=float)  # output

# scale units
xAll = xAll / np.amax(xAll, axis=0)  # scaling input data
y = y / 100  # scaling output data (max test score is 100)

# split data
X = np.split(xAll, [3])[0]  # training data
xPredicted = np.split(xAll, [3])[1]  # testing data

y = np.array(([92], [86], [89]), dtype=float)
y = y / 100  # max test score is 100


class Neural_Network(object):
    def __init__(self):
        #parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3

        #weights
        self.W1 = np.random.randn(
            self.inputSize,
            self.hiddenSize)  # (3x2) weight matrix from input to hidden layer
        self.W2 = np.random.randn(
            self.hiddenSize,
            self.outputSize)  # (3x1) weight matrix from hidden to output layer

    def forward(self, X):
        #forward propagation through our network
        self.z = np.dot(
            X,
            self.W1)  # dot product of X (input) and first set of 3x2 weights
        self.z2 = self.sigmoid(self.z)  # activation function
        self.z3 = np.dot(
            self.z2, self.W2
        )  # dot product of hidden layer (z2) and second set of 3x1 weights
        o = self.sigmoid(self.z3)  # final activation function
        return o

    def sigmoid(self, s):
        # activation function
        return 1 / (1 + np.exp(-s))

    def sigmoidPrime(self, s):
        #derivative of sigmoid
        return s * (1 - s)

    def backward(self, X, y, o):
        # backward propagate through the network
        self.o_error = y - o  # error in output
        self.o_delta = self.o_error * self.sigmoidPrime(
            o)  # applying derivative of sigmoid to error

        self.z2_error = self.o_delta.dot(
            self.W2.T
        )  # z2 error: how much our hidden layer weights contributed to output error
        self.z2_delta = self.z2_error * self.sigmoidPrime(
            self.z2)  # applying derivative of sigmoid to z2 error

        self.W1 += X.T.dot(
            self.z2_delta)  # adjusting first set (input --> hidden) weights
        self.W2 += self.z2.T.dot(
            self.o_delta)  # adjusting second set (hidden --> output) weights

    def train(self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)

    def saveWeights(self):
        np.savetxt("w1.txt", self.W1, fmt="%s")
        np.savetxt("w2.txt", self.W2, fmt="%s")

    def predict(self):
        print("Predicted data based on trained weights: ")
        print("Input (scaled): \n" + str(xPredicted))
        print("Output: \n" + str(self.forward(xPredicted)))


NN = Neural_Network()
for i in range(1000):  # trains the NN 1,000 times
    print("# " + str(i) + "\n")
    print("Input (scaled): \n" + str(X))
    print("Actual Output: \n" + str(y))
    print("Predicted Output: \n" + str(NN.forward(X)))
    print("Loss: \n" +
          str(np.mean(np.square(y - NN.forward(X)))))  # mean sum squared loss
    print("\n")
    NN.train(X, y)

NN.saveWeights()
NN.predict()

# 0

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.92113449]
 [0.8882471 ]
 [0.92130746]]
Loss: 
0.0005931141621779923


# 1

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.92064006]
 [0.88764857]
 [0.92080091]]
Loss: 
0.0005711829448672084


# 2

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.92015344]
 [0.88706   ]
 [0.92030217]]
Loss: 
0.0005501629745397154


# 3

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.91967477]
 [0.88648153]
 [0.91981137]]
Loss: 
0.0005300315568729541


# 4

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.91920415]
 [0.88591323]
 [0.91932862]]
Loss: 
0.0005107654768592623


# 5

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90677178]
 [0.87101994]
 [0.90645865]]
Loss: 
0.00018910402850057725


# 46

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90661139]
 [0.87082807]
 [0.90628961]]
Loss: 
0.00018728438826369148


# 47

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90645607]
 [0.87064218]
 [0.90612573]]
Loss: 
0.0001855776815174074


# 48

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9063057 ]
 [0.87046213]
 [0.90596688]]
Loss: 
0.00018397712146980006


# 49

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90616013]
 [0.87028776]
 [0.90581293]]
Loss: 
0.00018247628732625244


# 50

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]



Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90262579]
 [0.86593759]
 [0.90189465]]
Loss: 
0.0001595335691127899


# 108

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90260974]
 [0.8659151 ]
 [0.90187301]]
Loss: 
0.00015945927604387245


# 109

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90259436]
 [0.86589339]
 [0.90185206]]
Loss: 
0.00015938653790377555


# 110

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90257963]
 [0.86587245]
 [0.90183178]]
Loss: 
0.0001593152465784543


# 111

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90256553]
 [0.86585223]
 [0.90181214]]
Loss: 
0.00015924530151992548


# 112

Input (scaled): 
[[0.4 0.9]
 [0.2 0.

0.00015580338431196632


# 174

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90232971]
 [0.86534168]
 [0.90124649]]
Loss: 
0.00015575202754019817


# 175

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90233076]
 [0.8653392 ]
 [0.90124247]]
Loss: 
0.00015570070499649647


# 176

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90233187]
 [0.86533678]
 [0.90123851]]
Loss: 
0.00015564941583703535


# 177

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90233303]
 [0.86533443]
 [0.90123461]]
Loss: 
0.00015559815927738605


# 178

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90233424]
 [0.86533214]
 [0.90123076]]
Loss: 
0.0001555469345882812


# 179

Inpu

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90246625]
 [0.86525142]
 [0.90104325]]
Loss: 
0.00015232105897619577


# 243

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90246869]
 [0.86525063]
 [0.90104074]]
Loss: 
0.00015227139204173495


# 244

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90247113]
 [0.86524985]
 [0.90103825]]
Loss: 
0.00015222174684222916


# 245

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90247357]
 [0.86524907]
 [0.90103576]]
Loss: 
0.000152172123358911


# 246

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90247602]
 [0.8652483 ]
 [0.90103327]]
Loss: 
0.00015212252157337954


# 247

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5

Predicted Output: 
[[0.90258065]
 [0.86521888]
 [0.90093185]]
Loss: 
0.0001500586278510089


# 289

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90258316]
 [0.86521822]
 [0.90092949]]
Loss: 
0.00015000994437472533


# 290

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90258567]
 [0.86521757]
 [0.90092712]]
Loss: 
0.0001499612819444459


# 291

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90258818]
 [0.86521692]
 [0.90092475]]
Loss: 
0.0001499126405467809


# 292

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90259069]
 [0.86521626]
 [0.90092239]]
Loss: 
0.0001498640201683789


# 293

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9025932 ]
 [0.86

# 351

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90273843]
 [0.86517912]
 [0.90078477]]
Loss: 
0.0001470321508252569


# 352

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90274092]
 [0.86517851]
 [0.90078246]]
Loss: 
0.00014698476777883377


# 353

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90274341]
 [0.8651779 ]
 [0.90078015]]
Loss: 
0.00014693740496570247


# 354

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9027459 ]
 [0.86517728]
 [0.90077784]]
Loss: 
0.00014689006237334756


# 355

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90274839]
 [0.86517667]
 [0.90077554]]
Loss: 
0.00014684273998926043


# 356

Input (scaled): 
[[0.4 0.9]
 

0.00014436324732945333


# 409

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90288202]
 [0.86514407]
 [0.90065196]]
Loss: 
0.00014431699790361165


# 410

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90288448]
 [0.86514348]
 [0.90064969]]
Loss: 
0.00014427076801386474


# 411

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90288694]
 [0.86514288]
 [0.90064742]]
Loss: 
0.00014422455764827598


# 412

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90288939]
 [0.86514229]
 [0.90064515]]
Loss: 
0.00014417836679491187


# 413

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90289185]
 [0.86514169]
 [0.90064288]]
Loss: 
0.00014413219544184432


# 414

Inp

Predicted Output: 
[[0.90302127]
 [0.8651106 ]
 [0.90052343]]
Loss: 
0.00014171270939817456


# 467

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9030237 ]
 [0.86511002]
 [0.90052119]]
Loss: 
0.00014166757362197853


# 468

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90302612]
 [0.86510944]
 [0.90051896]]
Loss: 
0.0001416224567050443


# 469

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90302855]
 [0.86510886]
 [0.90051672]]
Loss: 
0.00014157735863597597


# 470

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90303097]
 [0.86510828]
 [0.90051448]]
Loss: 
0.0001415322794033935


# 471

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9030334 ]
 [0.

Loss: 
0.00013894952835479823


# 529

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90317304]
 [0.86507462]
 [0.90038357]]
Loss: 
0.00013890554065321378


# 530

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90317544]
 [0.86507406]
 [0.90038136]]
Loss: 
0.0001388615711216533


# 531

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90317783]
 [0.8650735 ]
 [0.90037916]]
Loss: 
0.00013881761974928445


# 532

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90318022]
 [0.86507293]
 [0.90037696]]
Loss: 
0.00013877368652527713


# 533

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90318261]
 [0.86507237]
 [0.90037476]]
Loss: 
0.00013872977143880995


# 53

 [0.89]]
Predicted Output: 
[[0.90328249]
 [0.865049  ]
 [0.90028285]]
Loss: 
0.00013690157399255724


# 576

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90328485]
 [0.86504845]
 [0.90028068]]
Loss: 
0.00013685842870677048


# 577

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90328722]
 [0.8650479 ]
 [0.9002785 ]]
Loss: 
0.00013681530109092873


# 578

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90328958]
 [0.86504735]
 [0.90027632]]
Loss: 
0.00013677219113459837


# 579

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90329195]
 [0.8650468 ]
 [0.90027415]]
Loss: 
0.00013672909882734972


# 580

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.903

 [0.89]]
Predicted Output: 
[[0.90342587]
 [0.86501583]
 [0.90015109]]
Loss: 
0.00013430167622759882


# 637

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9034282 ]
 [0.86501529]
 [0.90014894]]
Loss: 
0.00013425959000415365


# 638

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90343053]
 [0.86501476]
 [0.9001468 ]]
Loss: 
0.00013421752082894581


# 639

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90343287]
 [0.86501422]
 [0.90014466]]
Loss: 
0.00013417546869203258


# 640

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9034352 ]
 [0.86501369]
 [0.90014252]]
Loss: 
0.00013413343358347821


# 641

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.903

# 698

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90356961]
 [0.86498302]
 [0.9000192 ]]
Loss: 
0.00013172419687628933


# 699

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90357191]
 [0.8649825 ]
 [0.90001709]]
Loss: 
0.00013168314913423497


# 700

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90357421]
 [0.86498198]
 [0.90001498]]
Loss: 
0.00013164211783853403


# 701

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90357651]
 [0.86498146]
 [0.90001287]]
Loss: 
0.0001316011029797209


# 702

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90357882]
 [0.86498093]
 [0.90001076]]
Loss: 
0.00013156010454833092


# 703

Input (scaled): 
[[0.4 0.9]
 

# 751

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90369094]
 [0.86495567]
 [0.89990804]]
Loss: 
0.00012957110995662894


# 752

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90369322]
 [0.86495516]
 [0.89990596]]
Loss: 
0.00012953092099497106


# 753

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90369549]
 [0.86495465]
 [0.89990388]]
Loss: 
0.00012949074798787957


# 754

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90369777]
 [0.86495414]
 [0.8999018 ]]
Loss: 
0.00012945059092627417


# 755

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90370004]
 [0.86495363]
 [0.89989971]]
Loss: 
0.00012941044980107816


# 756

Input (scaled): 
[[0.4 0.9]



# 817

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9038401 ]
 [0.86492246]
 [0.89977162]]
Loss: 
0.0001269524503650063


# 818

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90384235]
 [0.86492196]
 [0.89976957]]
Loss: 
0.00012691329523741162


# 819

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90384459]
 [0.86492147]
 [0.89976752]]
Loss: 
0.00012687415547967681


# 820

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90384683]
 [0.86492097]
 [0.89976547]]
Loss: 
0.00012683503108317675


# 821

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90384908]
 [0.86492047]
 [0.89976342]]
Loss: 
0.00012679592203928655


# 822

Input (scaled): 
[[0.4 0.9]


Predicted Output: 
[[0.90399603]
 [0.86488822]
 [0.89962927]]
Loss: 
0.00012424824320749625


# 888

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90399824]
 [0.86488774]
 [0.89962725]]
Loss: 
0.00012421014348470828


# 889

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90400045]
 [0.86488726]
 [0.89962524]]
Loss: 
0.00012417205854334704


# 890

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90400266]
 [0.86488678]
 [0.89962322]]
Loss: 
0.00012413398837523098


# 891

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90400487]
 [0.8648863 ]
 [0.89962121]]
Loss: 
0.00012409593297219018


# 892

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90400708]
 [

 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90413442]
 [0.86485824]
 [0.89950317]]
Loss: 
0.00012187650766347596


# 951

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9041366 ]
 [0.86485777]
 [0.89950118]]
Loss: 
0.00012183932344077694


# 952

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90413878]
 [0.86485731]
 [0.8994992 ]]
Loss: 
0.00012180215349617944


# 953

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90414096]
 [0.86485684]
 [0.89949721]]
Loss: 
0.00012176499782188513


# 954

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90414314]
 [0.86485637]
 [0.89949523]]
Loss: 
0.00012172785641010112


# 955

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]